version: "3.8"
services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=udo_sigeit
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432"