name: Lint checks
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.1

      - name: Install Dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier

      - name: Run Eslint
        run: npm run eslint
